#!/bin/sh

wget -q https://www.mauritiuspost.mu/find-your-post-code/ -O - \
	| grep "option value" \
	| grep -v "disabled selected" \
	| sed 's/^.*value="//g' \
	| sed 's/".*$//g' \
	| shuf \
	| head -n 1
