#!/bin/sh

wget -q https://www.mauritiuspost.mu/find-your-post-code/ -O - \
| sed 's/<option/\n<option/g' \
| grep "option value" \
| grep -v "disabled selected" \
| sed 's/^.*value="//g' \
| sed 's/".*$//g' \
| sed "s/&#039;/'/g" \
| grep -v "Main Town / Village" \
| shuf \
| head -n 1
